name: Sync from Public ASD Blueprint

on:
    schedule:
      - cron: '0 0 * * *' # Runs daily at midnight UTC
    push:
      branches:
        - main # Trigger on any commit to the main branch
    workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y nodejs npm
          npm install @octokit/auth-app

      - name: Generate GitHub App Token
        id: generate_token
        run: |
          echo "import { createAppAuth } from '@octokit/auth-app';
          import { writeFile } from 'fs/promises';

          (async () => {
              const auth = createAppAuth({
                  appId: process.env.APP_ID,
                  privateKey: process.env.PRIVATE_KEY.replace(/\\n/g, '\\n'),
                  installationId: process.env.INSTALLATION_ID,
              });
              const { token } = await auth({ type: 'installation' });
              await writeFile('${{ github.workspace }}/auth-token.txt', token);
          })();" > generate-token.mjs
          node generate-token.mjs
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}

      - name: Read token into environment variable
        id: read_token
        run: echo "TOKEN=$(cat auth-token.txt)" >> $GITHUB_ENV

      - name: Checkout private repo with App token
        uses: actions/checkout@v3
        with:
          token: ${{ env.TOKEN }}
          repository: JayCloudLabs/asd_blueprint_data
          ref: main

      - name: Add public repo as upstream
        run: |
          git remote add upstream https://github.com/ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud.git
          git fetch upstream --tags

      - name: Sync data and tags
        run: |
          git merge upstream/main --allow-unrelated-histories -m "Merge from ASD-Blueprint-for-Secure-Cloud"
          git push origin main
          git push origin --tags
